package org.openflow.protocol.interfaces;

public enum OFBadMatchCode {
	OFPBMC_BAD_NW_ADDR_MASK,
	OFPBMC_BAD_FIELD,
	OFPBMC_BAD_MASK,
	OFPBMC_EPERM,
	OFPBMC_DUP_FIELD,
	OFPBMC_BAD_LEN,
	OFPBMC_BAD_TAG,
	OFPBMC_BAD_TYPE,
	OFPBMC_BAD_VALUE,
	OFPBMC_BAD_PREREQ,
	OFPBMC_BAD_WILDCARDS,
	OFPBMC_BAD_DL_ADDR_MASK
}