package org.openflow.protocol.interfaces;

public enum OFBadInstructionCode {
	OFPBIC_BAD_EXPERIMENTER,
	OFPBIC_BAD_TABLE_ID,
	OFPBIC_UNSUP_METADATA,
	OFPBIC_UNSUP_INST,
	OFPBIC_EPERM,
	OFPBIC_UNKNOWN_INST,
	OFPBIC_BAD_LEN,
	OFPBIC_UNSUP_METADATA_MASK,
	OFPBIC_BAD_EXP_TYPE
}