package org.openflow.protocol.interfaces;

public enum OFBadActionCode {
	BAD_QUEUE,
	EPERM,
	BAD_SET_TYPE,
	MATCH_INCONSISTENT,
	BAD_EXPERIMENTER,
	BAD_VENDOR_TYPE,
	BAD_TYPE,
	BAD_ARGUMENT,
	BAD_OUT_PORT,
	BAD_EXP_TYPE,
	BAD_TAG,
	BAD_SET_ARGUMENT,
	BAD_OUT_GROUP,
	TOO_MANY,
	UNSUPPORTED_ORDER,
	BAD_SET_LEN,
	BAD_VENDOR,
	BAD_LEN
}