package org.openflow.protocol.interfaces;

public enum OFBadRequestCode {
	OFPBRC_IS_SLAVE,
	OFPBRC_MULTIPART_BUFFER_OVERFLOW,
	OFPBRC_BAD_EXP_TYPE,
	OFPBRC_BAD_SUBTYPE,
	OFPBRC_BAD_VERSION,
	OFPBRC_BAD_VENDOR,
	OFPBRC_BAD_PACKET,
	OFPBRC_BAD_EXPERIMENTER,
	OFPBRC_BAD_LEN,
	OFPBRC_BUFFER_EMPTY,
	OFPBRC_BAD_PORT,
	OFPBRC_BUFFER_UNKNOWN,
	OFPBRC_BAD_TYPE,
	OFPBRC_BAD_TABLE_ID,
	OFPBRC_BAD_STAT,
	OFPBRC_BAD_MULTIPART,
	OFPBRC_EPERM
}