package org.openflow.protocol.interfaces;

public enum OFBadRequestCode {
	BAD_TABLE_ID,
	BUFFER_UNKNOWN,
	BAD_EXPERIMENTER,
	BAD_MULTIPART,
	EPERM,
	BUFFER_EMPTY,
	BAD_SUBTYPE,
	BAD_STAT,
	BAD_TYPE,
	IS_SLAVE,
	BAD_VERSION,
	BAD_PACKET,
	MULTIPART_BUFFER_OVERFLOW,
	BAD_EXP_TYPE,
	BAD_VENDOR,
	BAD_PORT,
	BAD_LEN
}