package org.openflow.protocol.interfaces;

public enum OFBadActionCode {
	OFPBAC_UNSUPPORTED_ORDER,
	OFPBAC_MATCH_INCONSISTENT,
	OFPBAC_BAD_EXP_TYPE,
	OFPBAC_BAD_VENDOR,
	OFPBAC_BAD_SET_ARGUMENT,
	OFPBAC_BAD_TYPE,
	OFPBAC_BAD_SET_LEN,
	OFPBAC_EPERM,
	OFPBAC_BAD_OUT_GROUP,
	OFPBAC_BAD_OUT_PORT,
	OFPBAC_BAD_ARGUMENT,
	OFPBAC_BAD_VENDOR_TYPE,
	OFPBAC_BAD_LEN,
	OFPBAC_BAD_SET_TYPE,
	OFPBAC_BAD_QUEUE,
	OFPBAC_BAD_TAG,
	OFPBAC_BAD_EXPERIMENTER,
	OFPBAC_TOO_MANY
}