package org.openflow.protocol.interfaces;

public enum OFDefinitions {
	SERIAL_NUMBER_LEN,
	OFP_ETH_ALEN,
	OFP_MAX_PORT_NAME_LEN,
	OFP_SSL_PORT,
	OFP_VLAN_NONE,
	OFP_FLOW_PERMANENT,
	DESCRIPTION_STRING_LEN,
	OFPQ_ALL,
	OFPQ_MIN_RATE_UNCFG,
	OFPFW_ICMP_TYPE,
	OFP_TCP_PORT,
	OFP_DL_TYPE_ETH2_CUTOFF,
	OFPFW_ICMP_CODE,
	OFP_DL_TYPE_NOT_ETH_TYPE,
	OFP_MAX_TABLE_NAME_LEN,
	OFP_DEFAULT_PRIORITY,
	OFP_NO_BUFFER,
	OFP_DEFAULT_MISS_SEND_LEN,
	OFPQ_MAX_RATE_UNCFG
}