package org.openflow.protocol.interfaces;

public enum OFDefinitions {
	ICMP_CODE,
	ALL,
	TCP_PORT,
	DEFAULT_MISS_SEND_LEN,
	NO_BUFFER,
	VLAN_NONE,
	NUMBER_LEN,
	DL_TYPE_ETH2_CUTOFF,
	MAX_PORT_NAME_LEN,
	SSL_PORT,
	MAX_RATE_UNCFG,
	STRING_LEN,
	FLOW_PERMANENT,
	ETH_ALEN,
	ICMP_TYPE,
	DL_TYPE_NOT_ETH_TYPE,
	MAX_TABLE_NAME_LEN,
	DEFAULT_PRIORITY,
	MIN_RATE_UNCFG
}