package org.openflow.protocol.interfaces;

public enum OFErrorCode {
	HELLO_FAILED,
	BAD_MATCH,
	BAD_ACTION,
	GROUP_MOD_FAILED,
	PORT_MOD_FAILED,
	FLOW_MOD_FAILED,
	SWITCH_CONFIG_FAILED,
	QUEUE_OP_FAILED,
	BAD_REQUEST,
	TABLE_FEATURES_FAILED,
	TABLE_MOD_FAILED,
	EXPERIMENTER,
	METER_MOD_FAILED,
	BAD_INSTRUCTION,
	ROLE_REQUEST_FAILED
}