package org.openflow.protocol.interfaces;

public enum OFErrorCode {
	OFPET_TABLE_MOD_FAILED,
	OFPET_BAD_MATCH,
	OFPET_SWITCH_CONFIG_FAILED,
	OFPET_FLOW_MOD_FAILED,
	OFPET_BAD_INSTRUCTION,
	OFPET_TABLE_FEATURES_FAILED,
	OFPET_GROUP_MOD_FAILED,
	OFPET_BAD_REQUEST,
	OFPET_EXPERIMENTER,
	OFPET_ROLE_REQUEST_FAILED,
	OFPET_METER_MOD_FAILED,
	OFPET_BAD_ACTION,
	OFPET_QUEUE_OP_FAILED,
	OFPET_PORT_MOD_FAILED,
	OFPET_HELLO_FAILED
}