package org.openflow.protocol.interfaces;

public enum OFFlowWildcards {
	OFPFW_ALL,
	OFPFW_DL_VLAN_PCP,
	OFPFW_NW_SRC_MASK,
	OFPFW_DL_DST,
	OFPFW_DL_SRC,
	OFPFW_TP_SRC,
	OFPFW_NW_SRC_SHIFT,
	OFPFW_TP_DST,
	OFPFW_NW_DST_BITS,
	OFPFW_NW_TOS,
	OFPFW_NW_DST_ALL,
	OFPFW_NW_SRC_BITS,
	OFPFW_NW_DST_SHIFT,
	OFPFW_NW_DST_MASK,
	OFPFW_IN_PORT,
	OFPFW_NW_PROTO,
	OFPFW_DL_VLAN,
	OFPFW_NW_SRC_ALL,
	OFPFW_DL_TYPE
}