package org.openflow.protocol.interfaces;

public enum OFFlowModFailedCode {
	OFPFMFC_ALL_TABLES_FULL,
	OFPFMFC_TABLE_FULL,
	OFPFMFC_UNSUPPORTED,
	OFPFMFC_BAD_EMERG_TIMEOUT,
	OFPFMFC_UNKNOWN,
	OFPFMFC_OVERLAP,
	OFPFMFC_BAD_FLAGS,
	OFPFMFC_EPERM,
	OFPFMFC_BAD_COMMAND,
	OFPFMFC_BAD_TABLE_ID,
	OFPFMFC_BAD_TIMEOUT
}