package org.openflow.protocol.interfaces;

public enum OFGroupModFailedCode {
	OFPGMFC_EPERM,
	OFPGMFC_BAD_BUCKET,
	OFPGMFC_BAD_WATCH,
	OFPGMFC_UNKNOWN_GROUP,
	OFPGMFC_CHAINED_GROUP,
	OFPGMFC_BAD_COMMAND,
	OFPGMFC_GROUP_EXISTS,
	OFPGMFC_OUT_OF_GROUPS,
	OFPGMFC_WEIGHT_UNSUPPORTED,
	OFPGMFC_CHAINING_UNSUPPORTED,
	OFPGMFC_BAD_TYPE,
	OFPGMFC_OUT_OF_BUCKETS,
	OFPGMFC_LOOP,
	OFPGMFC_INVALID_GROUP,
	OFPGMFC_WATCH_UNSUPPORTED
}