package org.openflow.protocol.interfaces;

public enum OFGroupModFailedCode {
	GROUP_EXISTS,
	BAD_WATCH,
	BAD_BUCKET,
	OUT_OF_GROUPS,
	OUT_OF_BUCKETS,
	WATCH_UNSUPPORTED,
	BAD_TYPE,
	EPERM,
	CHAINED_GROUP,
	BAD_COMMAND,
	INVALID_GROUP,
	CHAINING_UNSUPPORTED,
	WEIGHT_UNSUPPORTED,
	LOOP,
	UNKNOWN_GROUP
}