package org.openflow.protocol.interfaces;

public enum OFMeterModFailedCode {
	OFPMMFC_BAD_COMMAND,
	OFPMMFC_BAD_RATE,
	OFPMMFC_METER_EXISTS,
	OFPMMFC_UNKNOWN,
	OFPMMFC_BAD_BAND,
	OFPMMFC_BAD_BURST,
	OFPMMFC_OUT_OF_METERS,
	OFPMMFC_BAD_FLAGS,
	OFPMMFC_OUT_OF_BANDS,
	OFPMMFC_INVALID_METER,
	OFPMMFC_UNKNOWN_METER,
	OFPMMFC_BAD_BAND_VALUE
}