package org.openflow.protocol.interfaces;

public enum OFMultipartType {
	OFPMP_DESC,
	OFPMP_AGGREGATE,
	OFPMP_PORT_DESC,
	OFPMP_GROUP_FEATURES,
	OFPMP_GROUP,
	OFPMP_TABLE_FEATURES,
	OFPMP_FLOW,
	OFPMP_METER,
	OFPMP_PORT_STATS,
	OFPMP_METER_FEATURES,
	OFPMP_EXPERIMENTER,
	OFPMP_TABLE,
	OFPMP_QUEUE,
	OFPMP_GROUP_DESC,
	OFPMP_METER_CONFIG
}