package org.openflow.protocol.interfaces;

public enum OFPortFeatures {
	OFPPF_40GB_FD,
	OFPPF_COPPER,
	OFPPF_FIBER,
	OFPPF_1GB_FD,
	OFPPF_1GB_HD,
	OFPPF_AUTONEG,
	OFPPF_OTHER,
	OFPPF_100MB_HD,
	OFPPF_10MB_FD,
	OFPPF_10GB_FD,
	OFPPF_PAUSE_ASYM,
	OFPPF_PAUSE,
	OFPPF_10MB_HD,
	OFPPF_100GB_FD,
	OFPPF_100MB_FD,
	OFPPF_1TB_FD
}