package org.openflow.protocol.interfaces;

public enum OFTableFeaturePropertyType {
	OFPTFPT_EXPERIMENTER,
	OFPTFPT_WILDCARDS,
	OFPTFPT_APPLY_ACTIONS,
	OFPTFPT_MATCH,
	OFPTFPT_WRITE_SETFIELD,
	OFPTFPT_WRITE_ACTIONS_MISS,
	OFPTFPT_INSTRUCTIONS,
	OFPTFPT_APPLY_SETFIELD_MISS,
	OFPTFPT_NEXT_TABLES,
	OFPTFPT_APPLY_SETFIELD,
	OFPTFPT_NEXT_TABLES_MISS,
	OFPTFPT_EXPERIMENTER_MISS,
	OFPTFPT_WRITE_SETFIELD_MISS,
	OFPTFPT_INSTRUCTIONS_MISS,
	OFPTFPT_WRITE_ACTIONS,
	OFPTFPT_APPLY_ACTIONS_MISS
}