package org.openflow.protocol.interfaces;

public enum OFTableFeaturePropertyType {
	NEXT_TABLES_MISS,
	WILDCARDS,
	EXPERIMENTER_MISS,
	WRITE_ACTIONS,
	NEXT_TABLES,
	WRITE_ACTIONS_MISS,
	APPLY_SETFIELD_MISS,
	APPLY_ACTIONS_MISS,
	APPLY_ACTIONS,
	INSTRUCTIONS_MISS,
	WRITE_SETFIELD_MISS,
	EXPERIMENTER,
	WRITE_SETFIELD,
	APPLY_SETFIELD,
	MATCH,
	INSTRUCTIONS
}